/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * 42chess API
 * 42chess 온라인 체스 플랫폼 백엔드 API
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query"
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query"

import { api } from "../../lib/axios-mutator"
import type { BodyType, ErrorType } from "../../lib/axios-mutator"
import type {
  ActiveMatchResponseDto,
  ErrorResponseDto,
  MatchControllerGetUserHistoryParams,
  MatchDetailDto,
  MatchStartedDto,
  PaginatedMatchesDto,
  StartMatchDto,
} from "../model"

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K }
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    })
  }
  return result
}

/**
 * 매치메이킹/챌린지 모듈 도입 전까지의 임시 엔드포인트. opponent username으로 직접 매치를 연다.
 * @summary 새 매치 시작 (임시 API)
 */
export const matchControllerStart = (
  startMatchDto: BodyType<StartMatchDto>,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<MatchStartedDto>(
    {
      url: `/api/matches`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: startMatchDto,
      signal,
    },
    options,
  )
}

export const getMatchControllerStartMutationOptions = <
  TError = ErrorType<ErrorResponseDto>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof matchControllerStart>>,
    TError,
    { data: BodyType<StartMatchDto> },
    TContext
  >
  request?: SecondParameter<typeof api>
}): UseMutationOptions<
  Awaited<ReturnType<typeof matchControllerStart>>,
  TError,
  { data: BodyType<StartMatchDto> },
  TContext
> => {
  const mutationKey = ["matchControllerStart"]
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof matchControllerStart>>,
    { data: BodyType<StartMatchDto> }
  > = (props) => {
    const { data } = props ?? {}

    return matchControllerStart(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type MatchControllerStartMutationResult = NonNullable<
  Awaited<ReturnType<typeof matchControllerStart>>
>
export type MatchControllerStartMutationBody = BodyType<StartMatchDto>
export type MatchControllerStartMutationError = ErrorType<ErrorResponseDto>

/**
 * @summary 새 매치 시작 (임시 API)
 */
export const useMatchControllerStart = <TError = ErrorType<ErrorResponseDto>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof matchControllerStart>>,
      TError,
      { data: BodyType<StartMatchDto> },
      TContext
    >
    request?: SecondParameter<typeof api>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof matchControllerStart>>,
  TError,
  { data: BodyType<StartMatchDto> },
  TContext
> => {
  return useMutation(getMatchControllerStartMutationOptions(options), queryClient)
}
/**
 * Redis에 보관된 활성 매치 substrate를 반환한다. 없으면 `{ match: null }`을 반환한다. 관전 기능은 이후 목표에서 이 surface를 확장한다.
 * @summary 현재 인증 사용자의 진행 중 매치 조회
 */
export const matchControllerGetActive = (
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<ActiveMatchResponseDto>({ url: `/api/matches/active`, method: "GET", signal }, options)
}

export const getMatchControllerGetActiveQueryKey = () => {
  return [`/api/matches/active`] as const
}

export const getMatchControllerGetActiveQueryOptions = <
  TData = Awaited<ReturnType<typeof matchControllerGetActive>>,
  TError = ErrorType<ErrorResponseDto>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof matchControllerGetActive>>, TError, TData>
  >
  request?: SecondParameter<typeof api>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getMatchControllerGetActiveQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof matchControllerGetActive>>> = ({
    signal,
  }) => matchControllerGetActive(requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof matchControllerGetActive>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type MatchControllerGetActiveQueryResult = NonNullable<
  Awaited<ReturnType<typeof matchControllerGetActive>>
>
export type MatchControllerGetActiveQueryError = ErrorType<ErrorResponseDto>

export function useMatchControllerGetActive<
  TData = Awaited<ReturnType<typeof matchControllerGetActive>>,
  TError = ErrorType<ErrorResponseDto>,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof matchControllerGetActive>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof matchControllerGetActive>>,
          TError,
          Awaited<ReturnType<typeof matchControllerGetActive>>
        >,
        "initialData"
      >
    request?: SecondParameter<typeof api>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMatchControllerGetActive<
  TData = Awaited<ReturnType<typeof matchControllerGetActive>>,
  TError = ErrorType<ErrorResponseDto>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof matchControllerGetActive>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof matchControllerGetActive>>,
          TError,
          Awaited<ReturnType<typeof matchControllerGetActive>>
        >,
        "initialData"
      >
    request?: SecondParameter<typeof api>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMatchControllerGetActive<
  TData = Awaited<ReturnType<typeof matchControllerGetActive>>,
  TError = ErrorType<ErrorResponseDto>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof matchControllerGetActive>>, TError, TData>
    >
    request?: SecondParameter<typeof api>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 현재 인증 사용자의 진행 중 매치 조회
 */

export function useMatchControllerGetActive<
  TData = Awaited<ReturnType<typeof matchControllerGetActive>>,
  TError = ErrorType<ErrorResponseDto>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof matchControllerGetActive>>, TError, TData>
    >
    request?: SecondParameter<typeof api>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getMatchControllerGetActiveQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return withQueryKey(query, queryOptions.queryKey)
}

/**
 * 진행 중 매치의 실시간 상태는 Socket.IO `/match` namespace의 `state` 이벤트로 받는다.
 * @summary 종료된 매치 상세 조회 (PGN 포함)
 */
export const matchControllerGetDetail = (
  matchId: string,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<MatchDetailDto>({ url: `/api/matches/${matchId}`, method: "GET", signal }, options)
}

export const getMatchControllerGetDetailQueryKey = (matchId: string) => {
  return [`/api/matches/${matchId}`] as const
}

export const getMatchControllerGetDetailQueryOptions = <
  TData = Awaited<ReturnType<typeof matchControllerGetDetail>>,
  TError = ErrorType<ErrorResponseDto>,
>(
  matchId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof matchControllerGetDetail>>, TError, TData>
    >
    request?: SecondParameter<typeof api>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getMatchControllerGetDetailQueryKey(matchId)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof matchControllerGetDetail>>> = ({
    signal,
  }) => matchControllerGetDetail(matchId, requestOptions, signal)

  return {
    queryKey,
    queryFn,
    enabled: matchId !== null && matchId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof matchControllerGetDetail>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }
}

export type MatchControllerGetDetailQueryResult = NonNullable<
  Awaited<ReturnType<typeof matchControllerGetDetail>>
>
export type MatchControllerGetDetailQueryError = ErrorType<ErrorResponseDto>

export function useMatchControllerGetDetail<
  TData = Awaited<ReturnType<typeof matchControllerGetDetail>>,
  TError = ErrorType<ErrorResponseDto>,
>(
  matchId: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof matchControllerGetDetail>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof matchControllerGetDetail>>,
          TError,
          Awaited<ReturnType<typeof matchControllerGetDetail>>
        >,
        "initialData"
      >
    request?: SecondParameter<typeof api>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMatchControllerGetDetail<
  TData = Awaited<ReturnType<typeof matchControllerGetDetail>>,
  TError = ErrorType<ErrorResponseDto>,
>(
  matchId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof matchControllerGetDetail>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof matchControllerGetDetail>>,
          TError,
          Awaited<ReturnType<typeof matchControllerGetDetail>>
        >,
        "initialData"
      >
    request?: SecondParameter<typeof api>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMatchControllerGetDetail<
  TData = Awaited<ReturnType<typeof matchControllerGetDetail>>,
  TError = ErrorType<ErrorResponseDto>,
>(
  matchId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof matchControllerGetDetail>>, TError, TData>
    >
    request?: SecondParameter<typeof api>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 종료된 매치 상세 조회 (PGN 포함)
 */

export function useMatchControllerGetDetail<
  TData = Awaited<ReturnType<typeof matchControllerGetDetail>>,
  TError = ErrorType<ErrorResponseDto>,
>(
  matchId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof matchControllerGetDetail>>, TError, TData>
    >
    request?: SecondParameter<typeof api>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getMatchControllerGetDetailQueryOptions(matchId, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return withQueryKey(query, queryOptions.queryKey)
}

/**
 * @summary 유저 매치 히스토리 (페이지네이션)
 */
export const matchControllerGetUserHistory = (
  username: string,
  params?: MatchControllerGetUserHistoryParams,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<PaginatedMatchesDto>(
    { url: `/api/users/${username}/matches`, method: "GET", params, signal },
    options,
  )
}

export const getMatchControllerGetUserHistoryQueryKey = (
  username: string,
  params?: MatchControllerGetUserHistoryParams,
) => {
  return [`/api/users/${username}/matches`, ...(params ? [params] : [])] as const
}

export const getMatchControllerGetUserHistoryQueryOptions = <
  TData = Awaited<ReturnType<typeof matchControllerGetUserHistory>>,
  TError = ErrorType<ErrorResponseDto>,
>(
  username: string,
  params?: MatchControllerGetUserHistoryParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof matchControllerGetUserHistory>>, TError, TData>
    >
    request?: SecondParameter<typeof api>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getMatchControllerGetUserHistoryQueryKey(username, params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof matchControllerGetUserHistory>>> = ({
    signal,
  }) => matchControllerGetUserHistory(username, params, requestOptions, signal)

  return {
    queryKey,
    queryFn,
    enabled: username !== null && username !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof matchControllerGetUserHistory>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }
}

export type MatchControllerGetUserHistoryQueryResult = NonNullable<
  Awaited<ReturnType<typeof matchControllerGetUserHistory>>
>
export type MatchControllerGetUserHistoryQueryError = ErrorType<ErrorResponseDto>

export function useMatchControllerGetUserHistory<
  TData = Awaited<ReturnType<typeof matchControllerGetUserHistory>>,
  TError = ErrorType<ErrorResponseDto>,
>(
  username: string,
  params: undefined | MatchControllerGetUserHistoryParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof matchControllerGetUserHistory>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof matchControllerGetUserHistory>>,
          TError,
          Awaited<ReturnType<typeof matchControllerGetUserHistory>>
        >,
        "initialData"
      >
    request?: SecondParameter<typeof api>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMatchControllerGetUserHistory<
  TData = Awaited<ReturnType<typeof matchControllerGetUserHistory>>,
  TError = ErrorType<ErrorResponseDto>,
>(
  username: string,
  params?: MatchControllerGetUserHistoryParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof matchControllerGetUserHistory>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof matchControllerGetUserHistory>>,
          TError,
          Awaited<ReturnType<typeof matchControllerGetUserHistory>>
        >,
        "initialData"
      >
    request?: SecondParameter<typeof api>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMatchControllerGetUserHistory<
  TData = Awaited<ReturnType<typeof matchControllerGetUserHistory>>,
  TError = ErrorType<ErrorResponseDto>,
>(
  username: string,
  params?: MatchControllerGetUserHistoryParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof matchControllerGetUserHistory>>, TError, TData>
    >
    request?: SecondParameter<typeof api>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 유저 매치 히스토리 (페이지네이션)
 */

export function useMatchControllerGetUserHistory<
  TData = Awaited<ReturnType<typeof matchControllerGetUserHistory>>,
  TError = ErrorType<ErrorResponseDto>,
>(
  username: string,
  params?: MatchControllerGetUserHistoryParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof matchControllerGetUserHistory>>, TError, TData>
    >
    request?: SecondParameter<typeof api>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getMatchControllerGetUserHistoryQueryOptions(username, params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return withQueryKey(query, queryOptions.queryKey)
}
