/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * 42chess API
 * 42chess 온라인 체스 플랫폼 백엔드 API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod"

/**
 * 매치메이킹/챌린지 모듈 도입 전까지의 임시 엔드포인트. opponent username으로 직접 매치를 연다.
 * @summary 새 매치 시작 (임시 API)
 */
export const MatchControllerStartBody = zod.object({
  opponentUsername: zod.string(),
  timeControl: zod.enum(["BULLET", "BLITZ", "RAPID", "CLASSICAL"]),
  initialTimeSeconds: zod.number().describe("초 단위 (1-3600)"),
  incrementSeconds: zod.number().describe("초 단위 (0-60)"),
})

export const MatchControllerStartResponse = zod.object({
  matchId: zod.string(),
  whiteUserId: zod.string(),
  blackUserId: zod.string(),
  timeControl: zod.enum(["BULLET", "BLITZ", "RAPID", "CLASSICAL"]),
  initialTimeSeconds: zod.number(),
  incrementSeconds: zod.number(),
  fen: zod.string(),
  pgn: zod.string(),
  turnStartedAt: zod.string(),
  startedAt: zod.string(),
})

/**
 * Redis에 보관된 활성 매치 substrate를 반환한다. 없으면 `{ match: null }`을 반환한다. 관전 기능은 이후 목표에서 이 surface를 확장한다.
 * @summary 현재 인증 사용자의 진행 중 매치 조회
 */
export const MatchControllerGetActiveResponse = zod.object({
  match: zod
    .object({
      matchId: zod.string(),
      whiteUserId: zod.string(),
      blackUserId: zod.string(),
      turn: zod.enum(["white", "black"]),
      timeControl: zod.enum(["BULLET", "BLITZ", "RAPID", "CLASSICAL"]),
      initialTimeSeconds: zod.number(),
      incrementSeconds: zod.number(),
      whiteClockMs: zod.number(),
      blackClockMs: zod.number(),
      fen: zod.string(),
      pgn: zod.string(),
      turnStartedAt: zod.string(),
      startedAt: zod.string(),
    })
    .nullable(),
})

/**
 * 진행 중 매치의 실시간 상태는 Socket.IO `/match` namespace의 `state` 이벤트로 받는다.
 * @summary 종료된 매치 상세 조회 (PGN 포함)
 */
export const MatchControllerGetDetailParams = zod.object({
  matchId: zod.string(),
})

export const MatchControllerGetDetailResponse = zod.object({
  id: zod.string(),
  whiteUser: zod.object({
    username: zod.string(),
    displayName: zod.string(),
    avatarUrl: zod.looseObject({}).nullable(),
  }),
  blackUser: zod.object({
    username: zod.string(),
    displayName: zod.string(),
    avatarUrl: zod.looseObject({}).nullable(),
  }),
  result: zod.enum(["WHITE_WIN", "BLACK_WIN", "DRAW"]),
  resultReason: zod.enum(["CHECKMATE", "RESIGN", "TIMEOUT", "AGREEMENT", "STALEMATE", "ABANDONED"]),
  timeControl: zod.enum(["BULLET", "BLITZ", "RAPID", "CLASSICAL"]),
  initialTimeSeconds: zod.number(),
  incrementSeconds: zod.number(),
  pgn: zod.string().describe("Portable Game Notation 전체 기록"),
  whiteRatingBefore: zod.number(),
  whiteRatingAfter: zod.number(),
  blackRatingBefore: zod.number(),
  blackRatingAfter: zod.number(),
  startedAt: zod.string(),
  endedAt: zod.string(),
})

/**
 * @summary 유저 매치 히스토리 (페이지네이션)
 */
export const MatchControllerGetUserHistoryParams = zod.object({
  username: zod.string(),
})

export const matchControllerGetUserHistoryQueryPageDefault = 1
export const matchControllerGetUserHistoryQueryPageSizeDefault = 20

export const MatchControllerGetUserHistoryQueryParams = zod.object({
  timeControl: zod.enum(["BULLET", "BLITZ", "RAPID", "CLASSICAL"]).optional(),
  page: zod.number().default(matchControllerGetUserHistoryQueryPageDefault),
  pageSize: zod.number().default(matchControllerGetUserHistoryQueryPageSizeDefault),
})

export const MatchControllerGetUserHistoryResponse = zod.object({
  items: zod.array(
    zod.object({
      id: zod.string(),
      opponent: zod.object({
        username: zod.string(),
        displayName: zod.string(),
        avatarUrl: zod.looseObject({}).nullable(),
      }),
      color: zod.enum(["WHITE", "BLACK"]),
      result: zod.enum(["WIN", "LOSS", "DRAW"]),
      absoluteResult: zod.enum(["WHITE_WIN", "BLACK_WIN", "DRAW"]),
      resultReason: zod.enum([
        "CHECKMATE",
        "RESIGN",
        "TIMEOUT",
        "AGREEMENT",
        "STALEMATE",
        "ABANDONED",
      ]),
      timeControl: zod.enum(["BULLET", "BLITZ", "RAPID", "CLASSICAL"]),
      initialTimeSeconds: zod.number(),
      incrementSeconds: zod.number(),
      ratingBefore: zod.number(),
      ratingAfter: zod.number(),
      ratingDelta: zod.number().describe("ratingAfter - ratingBefore"),
      startedAt: zod.string(),
      endedAt: zod.string(),
    }),
  ),
  total: zod.number(),
  page: zod.number(),
  pageSize: zod.number(),
  hasNext: zod.boolean(),
})
