/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * 42chess API
 * 42chess 온라인 체스 플랫폼 백엔드 API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod"

/**
 * httpOnly 쿠키 `refresh_token`을 검증하고 새 access/refresh 토큰을 발급한다. 기존 refresh 토큰은 폐기(rotation).
 * @summary Refresh 토큰 회전
 */
export const AuthControllerRefreshResponse = zod.object({
  accessToken: zod.string().describe("새로 발급된 Access Token (JWT)"),
})
