/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * 42chess API
 * 42chess 온라인 체스 플랫폼 백엔드 API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod"

/**
 * Creates a local account, returns an access token, and sets the httpOnly refresh cookie.
 * @summary Local email/password signup
 */
export const AuthControllerSignupBody = zod.object({
  email: zod.string(),
  username: zod.string().describe("3-20 lowercase letters, digits, or underscore characters"),
  displayName: zod.string(),
  password: zod.string(),
  avatarUrl: zod.string().optional(),
})

export const AuthControllerSignupResponse = zod.object({
  accessToken: zod.string(),
  user: zod.object({
    id: zod.string(),
    username: zod.string(),
    displayName: zod.string(),
    email: zod.string(),
    avatarUrl: zod.looseObject({}).nullable(),
  }),
})

/**
 * Authenticates a local account, returns an access token, and sets the httpOnly refresh cookie.
 * @summary Local email/password login
 */
export const AuthControllerLoginBody = zod.object({
  email: zod.string(),
  password: zod.string(),
})

export const AuthControllerLoginResponse = zod.object({
  accessToken: zod.string(),
  user: zod.object({
    id: zod.string(),
    username: zod.string(),
    displayName: zod.string(),
    email: zod.string(),
    avatarUrl: zod.looseObject({}).nullable(),
  }),
})

/**
 * Alias for `GET /api/users/me` kept under auth to reduce client integration risk. Profile data is resolved by UsersService.
 * @summary Authenticated profile alias
 */
export const AuthControllerGetMeResponse = zod.object({
  id: zod.string().describe("CUID2"),
  username: zod.string(),
  displayName: zod.string(),
  avatarUrl: zod.looseObject({}).nullable(),
  createdAt: zod.string(),
  ratings: zod.array(
    zod.object({
      timeControl: zod.enum(["BULLET", "BLITZ", "RAPID", "CLASSICAL"]),
      rating: zod.number(),
      gamesPlayed: zod.number(),
    }),
  ),
  email: zod
    .looseObject({})
    .nullable()
    .describe("OAuth 프로바이더가 준 이메일. 타인 프로필에선 노출되지 않음"),
  usernameChangedAt: zod
    .looseObject({})
    .nullable()
    .describe("username 변경 시각. null이면 아직 변경 가능"),
})

/**
 * 서버가 Google OAuth 동의 화면으로 302 리다이렉트한다.
 * @summary Google OAuth 로그인 시작
 */
export const AuthControllerGoogleLoginResponse = zod.unknown()

/**
 * httpOnly 쿠키 `refresh_token`을 검증하고 새 access/refresh 토큰을 발급한다. 기존 refresh 토큰은 폐기(rotation).
 * @summary Refresh 토큰 회전
 */
export const AuthControllerRefreshResponse = zod.object({
  accessToken: zod.string().describe("새로 발급된 Access Token (JWT)"),
})

/**
 * 서버측 refresh 토큰을 폐기하고 쿠키를 삭제한다. Access 토큰은 클라이언트가 직접 폐기해야 한다.
 * @summary 로그아웃
 */
export const AuthControllerLogoutResponse = zod.void()
