/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * 42chess API
 * 42chess 온라인 체스 플랫폼 백엔드 API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod"

/**
 * @summary 내 프로필 조회
 */
export const UsersControllerGetMeResponse = zod.object({
  id: zod.string().describe("CUID2"),
  username: zod.string(),
  displayName: zod.string(),
  avatarUrl: zod.looseObject({}).nullable(),
  createdAt: zod.string(),
  ratings: zod.array(
    zod.object({
      timeControl: zod.enum(["BULLET", "BLITZ", "RAPID", "CLASSICAL"]),
      rating: zod.number(),
      gamesPlayed: zod.number(),
    }),
  ),
  email: zod
    .looseObject({})
    .nullable()
    .describe("OAuth 프로바이더가 준 이메일. 타인 프로필에선 노출되지 않음"),
  usernameChangedAt: zod
    .looseObject({})
    .nullable()
    .describe("username 변경 시각. null이면 아직 변경 가능"),
})

/**
 * @summary 내 프로필 수정 (displayName, avatarUrl)
 */
export const UsersControllerUpdateMeBody = zod.object({
  displayName: zod.string().optional(),
  avatarUrl: zod.looseObject({}).nullish(),
})

export const UsersControllerUpdateMeResponse = zod.object({
  id: zod.string().describe("CUID2"),
  username: zod.string(),
  displayName: zod.string(),
  avatarUrl: zod.looseObject({}).nullable(),
  createdAt: zod.string(),
  ratings: zod.array(
    zod.object({
      timeControl: zod.enum(["BULLET", "BLITZ", "RAPID", "CLASSICAL"]),
      rating: zod.number(),
      gamesPlayed: zod.number(),
    }),
  ),
  email: zod
    .looseObject({})
    .nullable()
    .describe("OAuth 프로바이더가 준 이메일. 타인 프로필에선 노출되지 않음"),
  usernameChangedAt: zod
    .looseObject({})
    .nullable()
    .describe("username 변경 시각. null이면 아직 변경 가능"),
})

/**
 * @summary username 변경 (계정당 1회만 허용)
 */
export const UsersControllerUpdateUsernameBody = zod.object({
  username: zod.string().describe("3-20자, 소문자\/숫자\/underscore만 허용"),
})

export const UsersControllerUpdateUsernameResponse = zod.object({
  id: zod.string().describe("CUID2"),
  username: zod.string(),
  displayName: zod.string(),
  avatarUrl: zod.looseObject({}).nullable(),
  createdAt: zod.string(),
  ratings: zod.array(
    zod.object({
      timeControl: zod.enum(["BULLET", "BLITZ", "RAPID", "CLASSICAL"]),
      rating: zod.number(),
      gamesPlayed: zod.number(),
    }),
  ),
  email: zod
    .looseObject({})
    .nullable()
    .describe("OAuth 프로바이더가 준 이메일. 타인 프로필에선 노출되지 않음"),
  usernameChangedAt: zod
    .looseObject({})
    .nullable()
    .describe("username 변경 시각. null이면 아직 변경 가능"),
})

/**
 * @summary 유저 공개 프로필 조회
 */
export const UsersControllerGetByUsernameParams = zod.object({
  username: zod.string(),
})

export const UsersControllerGetByUsernameResponse = zod.object({
  id: zod.string().describe("CUID2"),
  username: zod.string(),
  displayName: zod.string(),
  avatarUrl: zod.looseObject({}).nullable(),
  createdAt: zod.string(),
  ratings: zod.array(
    zod.object({
      timeControl: zod.enum(["BULLET", "BLITZ", "RAPID", "CLASSICAL"]),
      rating: zod.number(),
      gamesPlayed: zod.number(),
    }),
  ),
})
