/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * 42chess API
 * 42chess 온라인 체스 플랫폼 백엔드 API
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query"
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query"

import { api } from "../../lib/axios-mutator"
import type { BodyType, ErrorType } from "../../lib/axios-mutator"
import type {
  ErrorResponseDto,
  MyProfileDto,
  UpdateProfileDto,
  UpdateUsernameDto,
  UserProfileDto,
} from "../model"

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K }
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    })
  }
  return result
}

/**
 * @summary 내 프로필 조회
 */
export const usersControllerGetMe = (
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<MyProfileDto>({ url: `/api/users/me`, method: "GET", signal }, options)
}

export const getUsersControllerGetMeQueryKey = () => {
  return [`/api/users/me`] as const
}

export const getUsersControllerGetMeQueryOptions = <
  TData = Awaited<ReturnType<typeof usersControllerGetMe>>,
  TError = ErrorType<ErrorResponseDto>,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetMe>>, TError, TData>>
  request?: SecondParameter<typeof api>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getUsersControllerGetMeQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof usersControllerGetMe>>> = ({ signal }) =>
    usersControllerGetMe(requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof usersControllerGetMe>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UsersControllerGetMeQueryResult = NonNullable<
  Awaited<ReturnType<typeof usersControllerGetMe>>
>
export type UsersControllerGetMeQueryError = ErrorType<ErrorResponseDto>

export function useUsersControllerGetMe<
  TData = Awaited<ReturnType<typeof usersControllerGetMe>>,
  TError = ErrorType<ErrorResponseDto>,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetMe>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerGetMe>>,
          TError,
          Awaited<ReturnType<typeof usersControllerGetMe>>
        >,
        "initialData"
      >
    request?: SecondParameter<typeof api>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersControllerGetMe<
  TData = Awaited<ReturnType<typeof usersControllerGetMe>>,
  TError = ErrorType<ErrorResponseDto>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetMe>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerGetMe>>,
          TError,
          Awaited<ReturnType<typeof usersControllerGetMe>>
        >,
        "initialData"
      >
    request?: SecondParameter<typeof api>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersControllerGetMe<
  TData = Awaited<ReturnType<typeof usersControllerGetMe>>,
  TError = ErrorType<ErrorResponseDto>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetMe>>, TError, TData>
    >
    request?: SecondParameter<typeof api>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 내 프로필 조회
 */

export function useUsersControllerGetMe<
  TData = Awaited<ReturnType<typeof usersControllerGetMe>>,
  TError = ErrorType<ErrorResponseDto>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetMe>>, TError, TData>
    >
    request?: SecondParameter<typeof api>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getUsersControllerGetMeQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return withQueryKey(query, queryOptions.queryKey)
}

/**
 * @summary 내 프로필 수정 (displayName, avatarUrl)
 */
export const usersControllerUpdateMe = (
  updateProfileDto: BodyType<UpdateProfileDto>,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<MyProfileDto>(
    {
      url: `/api/users/me`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: updateProfileDto,
      signal,
    },
    options,
  )
}

export const getUsersControllerUpdateMeMutationOptions = <
  TError = ErrorType<ErrorResponseDto>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof usersControllerUpdateMe>>,
    TError,
    { data: BodyType<UpdateProfileDto> },
    TContext
  >
  request?: SecondParameter<typeof api>
}): UseMutationOptions<
  Awaited<ReturnType<typeof usersControllerUpdateMe>>,
  TError,
  { data: BodyType<UpdateProfileDto> },
  TContext
> => {
  const mutationKey = ["usersControllerUpdateMe"]
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof usersControllerUpdateMe>>,
    { data: BodyType<UpdateProfileDto> }
  > = (props) => {
    const { data } = props ?? {}

    return usersControllerUpdateMe(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type UsersControllerUpdateMeMutationResult = NonNullable<
  Awaited<ReturnType<typeof usersControllerUpdateMe>>
>
export type UsersControllerUpdateMeMutationBody = BodyType<UpdateProfileDto>
export type UsersControllerUpdateMeMutationError = ErrorType<ErrorResponseDto>

/**
 * @summary 내 프로필 수정 (displayName, avatarUrl)
 */
export const useUsersControllerUpdateMe = <
  TError = ErrorType<ErrorResponseDto>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof usersControllerUpdateMe>>,
      TError,
      { data: BodyType<UpdateProfileDto> },
      TContext
    >
    request?: SecondParameter<typeof api>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof usersControllerUpdateMe>>,
  TError,
  { data: BodyType<UpdateProfileDto> },
  TContext
> => {
  return useMutation(getUsersControllerUpdateMeMutationOptions(options), queryClient)
}
/**
 * 진행 중 매치가 있으면 에러. 모든 refresh 세션이 폐기된다.
 * @summary 계정 탈퇴 (soft-delete)
 */
export const usersControllerDeleteMe = (
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<void>({ url: `/api/users/me`, method: "DELETE", signal }, options)
}

export const getUsersControllerDeleteMeMutationOptions = <
  TError = ErrorType<ErrorResponseDto>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof usersControllerDeleteMe>>,
    TError,
    void,
    TContext
  >
  request?: SecondParameter<typeof api>
}): UseMutationOptions<
  Awaited<ReturnType<typeof usersControllerDeleteMe>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["usersControllerDeleteMe"]
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof usersControllerDeleteMe>>,
    void
  > = () => {
    return usersControllerDeleteMe(requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type UsersControllerDeleteMeMutationResult = NonNullable<
  Awaited<ReturnType<typeof usersControllerDeleteMe>>
>

export type UsersControllerDeleteMeMutationError = ErrorType<ErrorResponseDto>

/**
 * @summary 계정 탈퇴 (soft-delete)
 */
export const useUsersControllerDeleteMe = <
  TError = ErrorType<ErrorResponseDto>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof usersControllerDeleteMe>>,
      TError,
      void,
      TContext
    >
    request?: SecondParameter<typeof api>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof usersControllerDeleteMe>>,
  TError,
  void,
  TContext
> => {
  return useMutation(getUsersControllerDeleteMeMutationOptions(options), queryClient)
}
/**
 * @summary username 변경 (계정당 1회만 허용)
 */
export const usersControllerUpdateUsername = (
  updateUsernameDto: BodyType<UpdateUsernameDto>,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<MyProfileDto>(
    {
      url: `/api/users/me/username`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: updateUsernameDto,
      signal,
    },
    options,
  )
}

export const getUsersControllerUpdateUsernameMutationOptions = <
  TError = ErrorType<ErrorResponseDto>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof usersControllerUpdateUsername>>,
    TError,
    { data: BodyType<UpdateUsernameDto> },
    TContext
  >
  request?: SecondParameter<typeof api>
}): UseMutationOptions<
  Awaited<ReturnType<typeof usersControllerUpdateUsername>>,
  TError,
  { data: BodyType<UpdateUsernameDto> },
  TContext
> => {
  const mutationKey = ["usersControllerUpdateUsername"]
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof usersControllerUpdateUsername>>,
    { data: BodyType<UpdateUsernameDto> }
  > = (props) => {
    const { data } = props ?? {}

    return usersControllerUpdateUsername(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type UsersControllerUpdateUsernameMutationResult = NonNullable<
  Awaited<ReturnType<typeof usersControllerUpdateUsername>>
>
export type UsersControllerUpdateUsernameMutationBody = BodyType<UpdateUsernameDto>
export type UsersControllerUpdateUsernameMutationError = ErrorType<ErrorResponseDto>

/**
 * @summary username 변경 (계정당 1회만 허용)
 */
export const useUsersControllerUpdateUsername = <
  TError = ErrorType<ErrorResponseDto>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof usersControllerUpdateUsername>>,
      TError,
      { data: BodyType<UpdateUsernameDto> },
      TContext
    >
    request?: SecondParameter<typeof api>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof usersControllerUpdateUsername>>,
  TError,
  { data: BodyType<UpdateUsernameDto> },
  TContext
> => {
  return useMutation(getUsersControllerUpdateUsernameMutationOptions(options), queryClient)
}
/**
 * @summary 유저 공개 프로필 조회
 */
export const usersControllerGetByUsername = (
  username: string,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<UserProfileDto>({ url: `/api/users/${username}`, method: "GET", signal }, options)
}

export const getUsersControllerGetByUsernameQueryKey = (username: string) => {
  return [`/api/users/${username}`] as const
}

export const getUsersControllerGetByUsernameQueryOptions = <
  TData = Awaited<ReturnType<typeof usersControllerGetByUsername>>,
  TError = ErrorType<ErrorResponseDto>,
>(
  username: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetByUsername>>, TError, TData>
    >
    request?: SecondParameter<typeof api>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getUsersControllerGetByUsernameQueryKey(username)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof usersControllerGetByUsername>>> = ({
    signal,
  }) => usersControllerGetByUsername(username, requestOptions, signal)

  return {
    queryKey,
    queryFn,
    enabled: username !== null && username !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetByUsername>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }
}

export type UsersControllerGetByUsernameQueryResult = NonNullable<
  Awaited<ReturnType<typeof usersControllerGetByUsername>>
>
export type UsersControllerGetByUsernameQueryError = ErrorType<ErrorResponseDto>

export function useUsersControllerGetByUsername<
  TData = Awaited<ReturnType<typeof usersControllerGetByUsername>>,
  TError = ErrorType<ErrorResponseDto>,
>(
  username: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetByUsername>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerGetByUsername>>,
          TError,
          Awaited<ReturnType<typeof usersControllerGetByUsername>>
        >,
        "initialData"
      >
    request?: SecondParameter<typeof api>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersControllerGetByUsername<
  TData = Awaited<ReturnType<typeof usersControllerGetByUsername>>,
  TError = ErrorType<ErrorResponseDto>,
>(
  username: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetByUsername>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerGetByUsername>>,
          TError,
          Awaited<ReturnType<typeof usersControllerGetByUsername>>
        >,
        "initialData"
      >
    request?: SecondParameter<typeof api>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersControllerGetByUsername<
  TData = Awaited<ReturnType<typeof usersControllerGetByUsername>>,
  TError = ErrorType<ErrorResponseDto>,
>(
  username: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetByUsername>>, TError, TData>
    >
    request?: SecondParameter<typeof api>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 유저 공개 프로필 조회
 */

export function useUsersControllerGetByUsername<
  TData = Awaited<ReturnType<typeof usersControllerGetByUsername>>,
  TError = ErrorType<ErrorResponseDto>,
>(
  username: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetByUsername>>, TError, TData>
    >
    request?: SecondParameter<typeof api>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getUsersControllerGetByUsernameQueryOptions(username, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return withQueryKey(query, queryOptions.queryKey)
}
