/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * 42chess API
 * 42chess 온라인 체스 플랫폼 백엔드 API
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query"
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query"

import { api } from "../../lib/axios-mutator"
import type { BodyType, ErrorType } from "../../lib/axios-mutator"
import type {
  AddFriendDto,
  ErrorResponseDto,
  FriendListDto,
  FriendMutationResultDto,
} from "../model"

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K }
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    })
  }
  return result
}

/**
 * @summary List authenticated user friends
 */
export const friendsControllerList = (
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<FriendListDto>({ url: `/api/friends`, method: "GET", signal }, options)
}

export const getFriendsControllerListQueryKey = () => {
  return [`/api/friends`] as const
}

export const getFriendsControllerListQueryOptions = <
  TData = Awaited<ReturnType<typeof friendsControllerList>>,
  TError = ErrorType<ErrorResponseDto>,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof friendsControllerList>>, TError, TData>>
  request?: SecondParameter<typeof api>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getFriendsControllerListQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof friendsControllerList>>> = ({ signal }) =>
    friendsControllerList(requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof friendsControllerList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FriendsControllerListQueryResult = NonNullable<
  Awaited<ReturnType<typeof friendsControllerList>>
>
export type FriendsControllerListQueryError = ErrorType<ErrorResponseDto>

export function useFriendsControllerList<
  TData = Awaited<ReturnType<typeof friendsControllerList>>,
  TError = ErrorType<ErrorResponseDto>,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof friendsControllerList>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof friendsControllerList>>,
          TError,
          Awaited<ReturnType<typeof friendsControllerList>>
        >,
        "initialData"
      >
    request?: SecondParameter<typeof api>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFriendsControllerList<
  TData = Awaited<ReturnType<typeof friendsControllerList>>,
  TError = ErrorType<ErrorResponseDto>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof friendsControllerList>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof friendsControllerList>>,
          TError,
          Awaited<ReturnType<typeof friendsControllerList>>
        >,
        "initialData"
      >
    request?: SecondParameter<typeof api>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFriendsControllerList<
  TData = Awaited<ReturnType<typeof friendsControllerList>>,
  TError = ErrorType<ErrorResponseDto>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof friendsControllerList>>, TError, TData>
    >
    request?: SecondParameter<typeof api>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List authenticated user friends
 */

export function useFriendsControllerList<
  TData = Awaited<ReturnType<typeof friendsControllerList>>,
  TError = ErrorType<ErrorResponseDto>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof friendsControllerList>>, TError, TData>
    >
    request?: SecondParameter<typeof api>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getFriendsControllerListQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return withQueryKey(query, queryOptions.queryKey)
}

/**
 * @summary Add an immediate mutual friendship
 */
export const friendsControllerAdd = (
  addFriendDto: BodyType<AddFriendDto>,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<FriendMutationResultDto>(
    {
      url: `/api/friends`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: addFriendDto,
      signal,
    },
    options,
  )
}

export const getFriendsControllerAddMutationOptions = <
  TError = ErrorType<ErrorResponseDto>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof friendsControllerAdd>>,
    TError,
    { data: BodyType<AddFriendDto> },
    TContext
  >
  request?: SecondParameter<typeof api>
}): UseMutationOptions<
  Awaited<ReturnType<typeof friendsControllerAdd>>,
  TError,
  { data: BodyType<AddFriendDto> },
  TContext
> => {
  const mutationKey = ["friendsControllerAdd"]
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof friendsControllerAdd>>,
    { data: BodyType<AddFriendDto> }
  > = (props) => {
    const { data } = props ?? {}

    return friendsControllerAdd(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type FriendsControllerAddMutationResult = NonNullable<
  Awaited<ReturnType<typeof friendsControllerAdd>>
>
export type FriendsControllerAddMutationBody = BodyType<AddFriendDto>
export type FriendsControllerAddMutationError = ErrorType<ErrorResponseDto>

/**
 * @summary Add an immediate mutual friendship
 */
export const useFriendsControllerAdd = <TError = ErrorType<ErrorResponseDto>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof friendsControllerAdd>>,
      TError,
      { data: BodyType<AddFriendDto> },
      TContext
    >
    request?: SecondParameter<typeof api>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof friendsControllerAdd>>,
  TError,
  { data: BodyType<AddFriendDto> },
  TContext
> => {
  return useMutation(getFriendsControllerAddMutationOptions(options), queryClient)
}
/**
 * @summary Remove a mutual friendship
 */
export const friendsControllerRemove = (
  username: string,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<FriendMutationResultDto>(
    { url: `/api/friends/${username}`, method: "DELETE", signal },
    options,
  )
}

export const getFriendsControllerRemoveMutationOptions = <
  TError = ErrorType<ErrorResponseDto>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof friendsControllerRemove>>,
    TError,
    { username: string },
    TContext
  >
  request?: SecondParameter<typeof api>
}): UseMutationOptions<
  Awaited<ReturnType<typeof friendsControllerRemove>>,
  TError,
  { username: string },
  TContext
> => {
  const mutationKey = ["friendsControllerRemove"]
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof friendsControllerRemove>>,
    { username: string }
  > = (props) => {
    const { username } = props ?? {}

    return friendsControllerRemove(username, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type FriendsControllerRemoveMutationResult = NonNullable<
  Awaited<ReturnType<typeof friendsControllerRemove>>
>

export type FriendsControllerRemoveMutationError = ErrorType<ErrorResponseDto>

/**
 * @summary Remove a mutual friendship
 */
export const useFriendsControllerRemove = <
  TError = ErrorType<ErrorResponseDto>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof friendsControllerRemove>>,
      TError,
      { username: string },
      TContext
    >
    request?: SecondParameter<typeof api>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof friendsControllerRemove>>,
  TError,
  { username: string },
  TContext
> => {
  return useMutation(getFriendsControllerRemoveMutationOptions(options), queryClient)
}
