/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * 42chess API
 * 42chess 온라인 체스 플랫폼 백엔드 API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod"

/**
 * @summary List authenticated user friends
 */
export const FriendsControllerListResponse = zod.object({
  items: zod.array(
    zod.object({
      username: zod.string(),
      displayName: zod.string(),
      avatarUrl: zod.looseObject({}).nullable(),
    }),
  ),
})

/**
 * @summary Add an immediate mutual friendship
 */
export const FriendsControllerAddBody = zod.object({
  username: zod.string(),
})

export const FriendsControllerAddResponse = zod.object({
  targetUsername: zod.string(),
  status: zod.enum(["FRIENDSHIP_ACTIVE", "FRIENDSHIP_REMOVED"]),
})

/**
 * @summary Remove a mutual friendship
 */
export const FriendsControllerRemoveParams = zod.object({
  username: zod.string(),
})

export const FriendsControllerRemoveResponse = zod.object({
  targetUsername: zod.string(),
  status: zod.enum(["FRIENDSHIP_ACTIVE", "FRIENDSHIP_REMOVED"]),
})
