/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * 42chess API
 * 42chess 온라인 체스 플랫폼 백엔드 API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod"

/**
 * @summary List direct message conversations
 */
export const ChatControllerListConversationsResponse = zod.object({
  items: zod.array(
    zod.object({
      id: zod.string(),
      peerUsername: zod.string(),
      peerDisplayName: zod.string(),
      peerAvatarUrl: zod.looseObject({}).nullable(),
      lastMessageAt: zod.string(),
      lastMessageBody: zod.string(),
      lastMessageSenderUsername: zod.string(),
    }),
  ),
})

/**
 * @summary List direct message history with a user
 */
export const ChatControllerListMessagesParams = zod.object({
  username: zod.string(),
})

export const ChatControllerListMessagesResponse = zod.object({
  items: zod.array(
    zod.object({
      id: zod.string(),
      senderUsername: zod.string(),
      recipientUsername: zod.string(),
      body: zod.string(),
      createdAt: zod.string(),
    }),
  ),
})

/**
 * @summary Send and persist a direct message
 */
export const ChatControllerSendMessageParams = zod.object({
  username: zod.string(),
})

export const ChatControllerSendMessageBody = zod.object({
  body: zod.string(),
})

export const ChatControllerSendMessageResponse = zod.object({
  message: zod.object({
    id: zod.string(),
    senderUsername: zod.string(),
    recipientUsername: zod.string(),
    body: zod.string(),
    createdAt: zod.string(),
  }),
})
