/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * 42chess API
 * 42chess 온라인 체스 플랫폼 백엔드 API
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query"
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query"

import { api } from "../../lib/axios-mutator"
import type { BodyType, ErrorType } from "../../lib/axios-mutator"
import type {
  ChatMessageListDto,
  ConversationListDto,
  ErrorResponseDto,
  SendDirectMessageDto,
  SendDirectMessageResultDto,
} from "../model"

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K }
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    })
  }
  return result
}

/**
 * @summary List direct message conversations
 */
export const chatControllerListConversations = (
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<ConversationListDto>(
    { url: `/api/chat/conversations`, method: "GET", signal },
    options,
  )
}

export const getChatControllerListConversationsQueryKey = () => {
  return [`/api/chat/conversations`] as const
}

export const getChatControllerListConversationsQueryOptions = <
  TData = Awaited<ReturnType<typeof chatControllerListConversations>>,
  TError = ErrorType<ErrorResponseDto>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof chatControllerListConversations>>, TError, TData>
  >
  request?: SecondParameter<typeof api>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getChatControllerListConversationsQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof chatControllerListConversations>>> = ({
    signal,
  }) => chatControllerListConversations(requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof chatControllerListConversations>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ChatControllerListConversationsQueryResult = NonNullable<
  Awaited<ReturnType<typeof chatControllerListConversations>>
>
export type ChatControllerListConversationsQueryError = ErrorType<ErrorResponseDto>

export function useChatControllerListConversations<
  TData = Awaited<ReturnType<typeof chatControllerListConversations>>,
  TError = ErrorType<ErrorResponseDto>,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof chatControllerListConversations>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof chatControllerListConversations>>,
          TError,
          Awaited<ReturnType<typeof chatControllerListConversations>>
        >,
        "initialData"
      >
    request?: SecondParameter<typeof api>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useChatControllerListConversations<
  TData = Awaited<ReturnType<typeof chatControllerListConversations>>,
  TError = ErrorType<ErrorResponseDto>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof chatControllerListConversations>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof chatControllerListConversations>>,
          TError,
          Awaited<ReturnType<typeof chatControllerListConversations>>
        >,
        "initialData"
      >
    request?: SecondParameter<typeof api>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useChatControllerListConversations<
  TData = Awaited<ReturnType<typeof chatControllerListConversations>>,
  TError = ErrorType<ErrorResponseDto>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof chatControllerListConversations>>, TError, TData>
    >
    request?: SecondParameter<typeof api>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List direct message conversations
 */

export function useChatControllerListConversations<
  TData = Awaited<ReturnType<typeof chatControllerListConversations>>,
  TError = ErrorType<ErrorResponseDto>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof chatControllerListConversations>>, TError, TData>
    >
    request?: SecondParameter<typeof api>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getChatControllerListConversationsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return withQueryKey(query, queryOptions.queryKey)
}

/**
 * @summary List direct message history with a user
 */
export const chatControllerListMessages = (
  username: string,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<ChatMessageListDto>(
    { url: `/api/chat/conversations/${username}/messages`, method: "GET", signal },
    options,
  )
}

export const getChatControllerListMessagesQueryKey = (username: string) => {
  return [`/api/chat/conversations/${username}/messages`] as const
}

export const getChatControllerListMessagesQueryOptions = <
  TData = Awaited<ReturnType<typeof chatControllerListMessages>>,
  TError = ErrorType<ErrorResponseDto>,
>(
  username: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof chatControllerListMessages>>, TError, TData>
    >
    request?: SecondParameter<typeof api>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getChatControllerListMessagesQueryKey(username)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof chatControllerListMessages>>> = ({
    signal,
  }) => chatControllerListMessages(username, requestOptions, signal)

  return {
    queryKey,
    queryFn,
    enabled: username !== null && username !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof chatControllerListMessages>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }
}

export type ChatControllerListMessagesQueryResult = NonNullable<
  Awaited<ReturnType<typeof chatControllerListMessages>>
>
export type ChatControllerListMessagesQueryError = ErrorType<ErrorResponseDto>

export function useChatControllerListMessages<
  TData = Awaited<ReturnType<typeof chatControllerListMessages>>,
  TError = ErrorType<ErrorResponseDto>,
>(
  username: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof chatControllerListMessages>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof chatControllerListMessages>>,
          TError,
          Awaited<ReturnType<typeof chatControllerListMessages>>
        >,
        "initialData"
      >
    request?: SecondParameter<typeof api>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useChatControllerListMessages<
  TData = Awaited<ReturnType<typeof chatControllerListMessages>>,
  TError = ErrorType<ErrorResponseDto>,
>(
  username: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof chatControllerListMessages>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof chatControllerListMessages>>,
          TError,
          Awaited<ReturnType<typeof chatControllerListMessages>>
        >,
        "initialData"
      >
    request?: SecondParameter<typeof api>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useChatControllerListMessages<
  TData = Awaited<ReturnType<typeof chatControllerListMessages>>,
  TError = ErrorType<ErrorResponseDto>,
>(
  username: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof chatControllerListMessages>>, TError, TData>
    >
    request?: SecondParameter<typeof api>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List direct message history with a user
 */

export function useChatControllerListMessages<
  TData = Awaited<ReturnType<typeof chatControllerListMessages>>,
  TError = ErrorType<ErrorResponseDto>,
>(
  username: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof chatControllerListMessages>>, TError, TData>
    >
    request?: SecondParameter<typeof api>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getChatControllerListMessagesQueryOptions(username, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return withQueryKey(query, queryOptions.queryKey)
}

/**
 * @summary Send and persist a direct message
 */
export const chatControllerSendMessage = (
  username: string,
  sendDirectMessageDto: BodyType<SendDirectMessageDto>,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<SendDirectMessageResultDto>(
    {
      url: `/api/chat/conversations/${username}/messages`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: sendDirectMessageDto,
      signal,
    },
    options,
  )
}

export const getChatControllerSendMessageMutationOptions = <
  TError = ErrorType<ErrorResponseDto>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof chatControllerSendMessage>>,
    TError,
    { username: string; data: BodyType<SendDirectMessageDto> },
    TContext
  >
  request?: SecondParameter<typeof api>
}): UseMutationOptions<
  Awaited<ReturnType<typeof chatControllerSendMessage>>,
  TError,
  { username: string; data: BodyType<SendDirectMessageDto> },
  TContext
> => {
  const mutationKey = ["chatControllerSendMessage"]
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof chatControllerSendMessage>>,
    { username: string; data: BodyType<SendDirectMessageDto> }
  > = (props) => {
    const { username, data } = props ?? {}

    return chatControllerSendMessage(username, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type ChatControllerSendMessageMutationResult = NonNullable<
  Awaited<ReturnType<typeof chatControllerSendMessage>>
>
export type ChatControllerSendMessageMutationBody = BodyType<SendDirectMessageDto>
export type ChatControllerSendMessageMutationError = ErrorType<ErrorResponseDto>

/**
 * @summary Send and persist a direct message
 */
export const useChatControllerSendMessage = <
  TError = ErrorType<ErrorResponseDto>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof chatControllerSendMessage>>,
      TError,
      { username: string; data: BodyType<SendDirectMessageDto> },
      TContext
    >
    request?: SecondParameter<typeof api>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof chatControllerSendMessage>>,
  TError,
  { username: string; data: BodyType<SendDirectMessageDto> },
  TContext
> => {
  return useMutation(getChatControllerSendMessageMutationOptions(options), queryClient)
}
