/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * 42chess API
 * 42chess 온라인 체스 플랫폼 백엔드 API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod"

/**
 * @summary Set authenticated user presence status
 */
export const PresenceControllerUpdateMeBody = zod.object({
  status: zod.enum(["ONLINE", "AWAY", "OFFLINE"]),
})

export const PresenceControllerUpdateMeResponse = zod.object({
  username: zod.string(),
  status: zod.enum(["ONLINE", "AWAY", "OFFLINE"]),
  lastSeenAt: zod.looseObject({}).nullable(),
})

/**
 * Pass a comma-separated `usernames` query value, for example `alice,bob`.
 * @summary List presence status for usernames
 */
export const PresenceControllerListQueryParams = zod.object({
  usernames: zod.string().optional(),
})

export const PresenceControllerListResponse = zod.object({
  items: zod.array(
    zod.object({
      username: zod.string(),
      status: zod.enum(["ONLINE", "AWAY", "OFFLINE"]),
      lastSeenAt: zod.looseObject({}).nullable(),
    }),
  ),
})

/**
 * @summary Get presence status by username
 */
export const PresenceControllerGetByUsernameParams = zod.object({
  username: zod.string(),
})

export const PresenceControllerGetByUsernameResponse = zod.object({
  username: zod.string(),
  status: zod.enum(["ONLINE", "AWAY", "OFFLINE"]),
  lastSeenAt: zod.looseObject({}).nullable(),
})
