/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * 42chess API
 * 42chess 온라인 체스 플랫폼 백엔드 API
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query"
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query"

import { api } from "../../lib/axios-mutator"
import type { BodyType, ErrorType } from "../../lib/axios-mutator"
import type {
  ErrorResponseDto,
  PresenceControllerListParams,
  PresenceListDto,
  PresenceStatusDto,
  UpdatePresenceDto,
} from "../model"

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K }
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    })
  }
  return result
}

/**
 * @summary Set authenticated user presence status
 */
export const presenceControllerUpdateMe = (
  updatePresenceDto: BodyType<UpdatePresenceDto>,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<PresenceStatusDto>(
    {
      url: `/api/presence/me`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: updatePresenceDto,
      signal,
    },
    options,
  )
}

export const getPresenceControllerUpdateMeMutationOptions = <
  TError = ErrorType<ErrorResponseDto>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof presenceControllerUpdateMe>>,
    TError,
    { data: BodyType<UpdatePresenceDto> },
    TContext
  >
  request?: SecondParameter<typeof api>
}): UseMutationOptions<
  Awaited<ReturnType<typeof presenceControllerUpdateMe>>,
  TError,
  { data: BodyType<UpdatePresenceDto> },
  TContext
> => {
  const mutationKey = ["presenceControllerUpdateMe"]
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof presenceControllerUpdateMe>>,
    { data: BodyType<UpdatePresenceDto> }
  > = (props) => {
    const { data } = props ?? {}

    return presenceControllerUpdateMe(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PresenceControllerUpdateMeMutationResult = NonNullable<
  Awaited<ReturnType<typeof presenceControllerUpdateMe>>
>
export type PresenceControllerUpdateMeMutationBody = BodyType<UpdatePresenceDto>
export type PresenceControllerUpdateMeMutationError = ErrorType<ErrorResponseDto>

/**
 * @summary Set authenticated user presence status
 */
export const usePresenceControllerUpdateMe = <
  TError = ErrorType<ErrorResponseDto>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof presenceControllerUpdateMe>>,
      TError,
      { data: BodyType<UpdatePresenceDto> },
      TContext
    >
    request?: SecondParameter<typeof api>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof presenceControllerUpdateMe>>,
  TError,
  { data: BodyType<UpdatePresenceDto> },
  TContext
> => {
  return useMutation(getPresenceControllerUpdateMeMutationOptions(options), queryClient)
}
/**
 * Pass a comma-separated `usernames` query value, for example `alice,bob`.
 * @summary List presence status for usernames
 */
export const presenceControllerList = (
  params?: PresenceControllerListParams,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<PresenceListDto>({ url: `/api/presence`, method: "GET", params, signal }, options)
}

export const getPresenceControllerListQueryKey = (params?: PresenceControllerListParams) => {
  return [`/api/presence`, ...(params ? [params] : [])] as const
}

export const getPresenceControllerListQueryOptions = <
  TData = Awaited<ReturnType<typeof presenceControllerList>>,
  TError = ErrorType<unknown>,
>(
  params?: PresenceControllerListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof presenceControllerList>>, TError, TData>
    >
    request?: SecondParameter<typeof api>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getPresenceControllerListQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof presenceControllerList>>> = ({ signal }) =>
    presenceControllerList(params, requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof presenceControllerList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PresenceControllerListQueryResult = NonNullable<
  Awaited<ReturnType<typeof presenceControllerList>>
>
export type PresenceControllerListQueryError = ErrorType<unknown>

export function usePresenceControllerList<
  TData = Awaited<ReturnType<typeof presenceControllerList>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | PresenceControllerListParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof presenceControllerList>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof presenceControllerList>>,
          TError,
          Awaited<ReturnType<typeof presenceControllerList>>
        >,
        "initialData"
      >
    request?: SecondParameter<typeof api>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePresenceControllerList<
  TData = Awaited<ReturnType<typeof presenceControllerList>>,
  TError = ErrorType<unknown>,
>(
  params?: PresenceControllerListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof presenceControllerList>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof presenceControllerList>>,
          TError,
          Awaited<ReturnType<typeof presenceControllerList>>
        >,
        "initialData"
      >
    request?: SecondParameter<typeof api>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePresenceControllerList<
  TData = Awaited<ReturnType<typeof presenceControllerList>>,
  TError = ErrorType<unknown>,
>(
  params?: PresenceControllerListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof presenceControllerList>>, TError, TData>
    >
    request?: SecondParameter<typeof api>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List presence status for usernames
 */

export function usePresenceControllerList<
  TData = Awaited<ReturnType<typeof presenceControllerList>>,
  TError = ErrorType<unknown>,
>(
  params?: PresenceControllerListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof presenceControllerList>>, TError, TData>
    >
    request?: SecondParameter<typeof api>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getPresenceControllerListQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return withQueryKey(query, queryOptions.queryKey)
}

/**
 * @summary Get presence status by username
 */
export const presenceControllerGetByUsername = (
  username: string,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<PresenceStatusDto>(
    { url: `/api/presence/${username}`, method: "GET", signal },
    options,
  )
}

export const getPresenceControllerGetByUsernameQueryKey = (username: string) => {
  return [`/api/presence/${username}`] as const
}

export const getPresenceControllerGetByUsernameQueryOptions = <
  TData = Awaited<ReturnType<typeof presenceControllerGetByUsername>>,
  TError = ErrorType<ErrorResponseDto>,
>(
  username: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof presenceControllerGetByUsername>>, TError, TData>
    >
    request?: SecondParameter<typeof api>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getPresenceControllerGetByUsernameQueryKey(username)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof presenceControllerGetByUsername>>> = ({
    signal,
  }) => presenceControllerGetByUsername(username, requestOptions, signal)

  return {
    queryKey,
    queryFn,
    enabled: username !== null && username !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof presenceControllerGetByUsername>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PresenceControllerGetByUsernameQueryResult = NonNullable<
  Awaited<ReturnType<typeof presenceControllerGetByUsername>>
>
export type PresenceControllerGetByUsernameQueryError = ErrorType<ErrorResponseDto>

export function usePresenceControllerGetByUsername<
  TData = Awaited<ReturnType<typeof presenceControllerGetByUsername>>,
  TError = ErrorType<ErrorResponseDto>,
>(
  username: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof presenceControllerGetByUsername>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof presenceControllerGetByUsername>>,
          TError,
          Awaited<ReturnType<typeof presenceControllerGetByUsername>>
        >,
        "initialData"
      >
    request?: SecondParameter<typeof api>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePresenceControllerGetByUsername<
  TData = Awaited<ReturnType<typeof presenceControllerGetByUsername>>,
  TError = ErrorType<ErrorResponseDto>,
>(
  username: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof presenceControllerGetByUsername>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof presenceControllerGetByUsername>>,
          TError,
          Awaited<ReturnType<typeof presenceControllerGetByUsername>>
        >,
        "initialData"
      >
    request?: SecondParameter<typeof api>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePresenceControllerGetByUsername<
  TData = Awaited<ReturnType<typeof presenceControllerGetByUsername>>,
  TError = ErrorType<ErrorResponseDto>,
>(
  username: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof presenceControllerGetByUsername>>, TError, TData>
    >
    request?: SecondParameter<typeof api>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get presence status by username
 */

export function usePresenceControllerGetByUsername<
  TData = Awaited<ReturnType<typeof presenceControllerGetByUsername>>,
  TError = ErrorType<ErrorResponseDto>,
>(
  username: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof presenceControllerGetByUsername>>, TError, TData>
    >
    request?: SecondParameter<typeof api>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getPresenceControllerGetByUsernameQueryOptions(username, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return withQueryKey(query, queryOptions.queryKey)
}
