/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * 42chess API
 * 42chess 온라인 체스 플랫폼 백엔드 API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod"

export const HealthControllerCheckResponse = zod.object({
  status: zod.string().optional(),
  info: zod
    .record(
      zod.string(),
      zod.object({
        status: zod.string(),
      }),
    )
    .nullish(),
  error: zod
    .record(
      zod.string(),
      zod.object({
        status: zod.string(),
      }),
    )
    .nullish(),
  details: zod
    .record(
      zod.string(),
      zod.object({
        status: zod.string(),
      }),
    )
    .optional(),
})
