/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * 42chess API
 * 42chess 온라인 체스 플랫폼 백엔드 API
 * OpenAPI spec version: 0.1.0
 */

/**
 * i18n 치환 변수 및 추가 메타데이터
 */
export type ErrorResponseDtoContext = { [key: string]: unknown }
