/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * 42chess API
 * 42chess 온라인 체스 플랫폼 백엔드 API
 * OpenAPI spec version: 0.1.0
 */
import type { ErrorResponseDtoContext } from "./errorResponseDtoContext.zod"

export interface ErrorResponseDto {
  statusCode: number
  error: string
  /** 프론트에서 i18n 분기에 사용하는 에러 식별자 */
  code: string
  /** 개발자용 영어 메시지 (사용자 UI 표시 금지) */
  message: string
  /** i18n 치환 변수 및 추가 메타데이터 */
  context?: ErrorResponseDtoContext
  timestamp: string
  path: string
  traceId: string
}
