/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * 42chess API
 * 42chess 온라인 체스 플랫폼 백엔드 API
 * OpenAPI spec version: 0.1.0
 */
import type { HealthControllerCheck200Details } from "./healthControllerCheck200Details"
import type { HealthControllerCheck200Error } from "./healthControllerCheck200Error"
import type { HealthControllerCheck200Info } from "./healthControllerCheck200Info"

export type HealthControllerCheck200 = {
  status?: string
  /** @nullable */
  info?: HealthControllerCheck200Info
  /** @nullable */
  error?: HealthControllerCheck200Error
  details?: HealthControllerCheck200Details
}
