/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * 42chess API
 * 42chess 온라인 체스 플랫폼 백엔드 API
 * OpenAPI spec version: 0.1.0
 */

/**
 * @nullable
 */
export type HealthControllerCheck200Info = {
  [key: string]: {
    status: string
    [key: string]: unknown
  }
} | null
