/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * 42chess API
 * 42chess 온라인 체스 플랫폼 백엔드 API
 * OpenAPI spec version: 0.1.0
 */
import type { MatchStartedDtoTimeControl } from "./matchStartedDtoTimeControl.zod"

export interface MatchStartedDto {
  matchId: string
  whiteUserId: string
  blackUserId: string
  timeControl: MatchStartedDtoTimeControl
  initialTimeSeconds: number
  incrementSeconds: number
  fen: string
  pgn: string
  turnStartedAt: string
  startedAt: string
}
