/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * 42chess API
 * 42chess 온라인 체스 플랫폼 백엔드 API
 * OpenAPI spec version: 0.1.0
 */
import type { MatchOpponentDto } from "./matchOpponentDto"
import type { MatchSummaryDtoAbsoluteResult } from "./matchSummaryDtoAbsoluteResult"
import type { MatchSummaryDtoColor } from "./matchSummaryDtoColor"
import type { MatchSummaryDtoResult } from "./matchSummaryDtoResult"
import type { MatchSummaryDtoResultReason } from "./matchSummaryDtoResultReason"
import type { MatchSummaryDtoTimeControl } from "./matchSummaryDtoTimeControl"

export interface MatchSummaryDto {
  id: string
  opponent: MatchOpponentDto
  color: MatchSummaryDtoColor
  result: MatchSummaryDtoResult
  absoluteResult: MatchSummaryDtoAbsoluteResult
  resultReason: MatchSummaryDtoResultReason
  timeControl: MatchSummaryDtoTimeControl
  initialTimeSeconds: number
  incrementSeconds: number
  ratingBefore: number
  ratingAfter: number
  /** ratingAfter - ratingBefore */
  ratingDelta: number
  startedAt: string
  endedAt: string
}
