/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * 42chess API
 * 42chess 온라인 체스 플랫폼 백엔드 API
 * OpenAPI spec version: 0.1.0
 */
import type { MatchDetailDtoResult } from "./matchDetailDtoResult.zod"
import type { MatchDetailDtoResultReason } from "./matchDetailDtoResultReason.zod"
import type { MatchDetailDtoTimeControl } from "./matchDetailDtoTimeControl.zod"
import type { MatchOpponentDto } from "./matchOpponentDto.zod"

export interface MatchDetailDto {
  id: string
  whiteUser: MatchOpponentDto
  blackUser: MatchOpponentDto
  result: MatchDetailDtoResult
  resultReason: MatchDetailDtoResultReason
  timeControl: MatchDetailDtoTimeControl
  initialTimeSeconds: number
  incrementSeconds: number
  /** Portable Game Notation 전체 기록 */
  pgn: string
  whiteRatingBefore: number
  whiteRatingAfter: number
  blackRatingBefore: number
  blackRatingAfter: number
  startedAt: string
  endedAt: string
}
