/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * 42chess API
 * 42chess 온라인 체스 플랫폼 백엔드 API
 * OpenAPI spec version: 0.1.0
 */

/**
 * username 변경 시각. null이면 아직 변경 가능
 * @nullable
 */
export type MyProfileDtoUsernameChangedAt = { [key: string]: unknown } | null
