/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * 42chess API
 * 42chess 온라인 체스 플랫폼 백엔드 API
 * OpenAPI spec version: 0.1.0
 */

/**
 * OAuth 프로바이더가 준 이메일. 타인 프로필에선 노출되지 않음
 * @nullable
 */
export type MyProfileDtoEmail = { [key: string]: unknown } | null
