/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * 42chess API
 * 42chess 온라인 체스 플랫폼 백엔드 API
 * OpenAPI spec version: 0.1.0
 */
import type { MyProfileDtoAvatarUrl } from "./myProfileDtoAvatarUrl"
import type { MyProfileDtoEmail } from "./myProfileDtoEmail"
import type { MyProfileDtoUsernameChangedAt } from "./myProfileDtoUsernameChangedAt"
import type { RatingDto } from "./ratingDto"

export interface MyProfileDto {
  /** CUID2 */
  id: string
  username: string
  displayName: string
  /** @nullable */
  avatarUrl: MyProfileDtoAvatarUrl
  createdAt: string
  ratings: RatingDto[]
  /**
   * OAuth 프로바이더가 준 이메일. 타인 프로필에선 노출되지 않음
   * @nullable
   */
  email: MyProfileDtoEmail
  /**
   * username 변경 시각. null이면 아직 변경 가능
   * @nullable
   */
  usernameChangedAt: MyProfileDtoUsernameChangedAt
}
