/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * 42chess API
 * 42chess 온라인 체스 플랫폼 백엔드 API
 * OpenAPI spec version: 0.1.0
 */

export type RatingDtoTimeControl = (typeof RatingDtoTimeControl)[keyof typeof RatingDtoTimeControl]

export const RatingDtoTimeControl = {
  BULLET: "BULLET",
  BLITZ: "BLITZ",
  RAPID: "RAPID",
  CLASSICAL: "CLASSICAL",
} as const
