/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * 42chess API
 * 42chess 온라인 체스 플랫폼 백엔드 API
 * OpenAPI spec version: 0.1.0
 */

export type SendDirectMessageResultDtoStatus =
  (typeof SendDirectMessageResultDtoStatus)[keyof typeof SendDirectMessageResultDtoStatus]

export const SendDirectMessageResultDtoStatus = {
  SUBSTRATE_ONLY: "SUBSTRATE_ONLY",
} as const
