/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * 42chess API
 * 42chess 온라인 체스 플랫폼 백엔드 API
 * OpenAPI spec version: 0.1.0
 */
import type { StartMatchDtoTimeControl } from "./startMatchDtoTimeControl"

export interface StartMatchDto {
  opponentUsername: string
  timeControl: StartMatchDtoTimeControl
  /** 초 단위 (1-3600) */
  initialTimeSeconds: number
  /** 초 단위 (0-60) */
  incrementSeconds: number
}
