/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * 42chess API
 * 42chess 온라인 체스 플랫폼 백엔드 API
 * OpenAPI spec version: 0.1.0
 */

export interface UpdateUsernameDto {
  /** 3-20자, 소문자/숫자/underscore만 허용 */
  username: string
}
