/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * 42chess API
 * 42chess 온라인 체스 플랫폼 백엔드 API
 * OpenAPI spec version: 0.1.0
 */
import type { RatingDto } from "./ratingDto"
import type { UserProfileDtoAvatarUrl } from "./userProfileDtoAvatarUrl"

export interface UserProfileDto {
  /** CUID2 */
  id: string
  username: string
  displayName: string
  /** @nullable */
  avatarUrl: UserProfileDtoAvatarUrl
  createdAt: string
  ratings: RatingDto[]
}
